ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - name: webserver
    command: npx --yes http-server -c-1 # webserver on port 8080 no cache
  - name: shell
    init: git config pull.rebase false
    command: >
vscode:
  extensions:
    - mhutchie.git-graph # add graphical viewer for branches and commits, click on button in Source-Code tab
    - adamraichu.pdf-viewer # add pdf-viewer for syntaxblad

